/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'description' : string,
  'iconName' : string,
}
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
  'image' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'seedData' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];